apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: {{ .Values.imagetag }}
          env:
            - name: NODE_ENV_DB_URL
              value: {{ .Values.mongodburl }}
            - name: NODE_ENV_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: NODE_ENV_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          ports:
            - containerPort: 5000